language: node_js
node_js: node
deploy: true
  provider: heroku
  api_key: "27f509aa-2181-41cc-b589-d11172297e88"
    secure: gPFpDnBQhBAjplOquq0d6khPDrUNT1DGI7dTsfYhGtYOCY2trYlkFrEdWRa4rf4Ao5mBP8qNonPVagvF34EmFeVJFS6UCE0aqfOUs374lnHKmJ3GuEyjYdoMrqpYVF/IXlgepRM4SbJ0t+Isvk2fwTA/XkQlzl96fzcEYmgj30IbxsZtnx2/BqOmt4IJ+9fDn1UBJ520kUfBN3TZMqbAXTcep0RXFsYUOwPZJvcbcEqC00mKUwNLDk7vI1QH/TI0/dLLzodTUx5TjUkzpnBa35mTVNKcSjx0cyhfqTizongGlm+T6vTLKS/zUM1pWD9tw7pjPzO5pkplwhvbK04vCy0JCuSGUaXGdgsl27fjeW6fJ4oxW5YfhZ3GsUPnGPHSZYLdmEjPTs4GtOFoDDSoOlm9O56zdPCg7+mNP7xhg1c18sORglVOwLI35GJ0D0wLPHwib6ABOLNfXAW7j7XrXNq8iqmhQTz9z9ZYMUruT3IDDkTTTIAcAr/wcen9Xn9UhIAUAoPdcycLmUnoYUi3eG+vgdA3GsCahpRV/SCVrtmkAqpwHK9SOl2U6IQa+SsZr9bNgF8TzJNiKkUx7RiLUqBHUoa6lv3SgT4V0ghHrcGiEYFPo3FIxnsXTCPdGsUp/E5oqR8MTX5/UAQSrbICMGWHWgNRBgxHr1JbW/KtF7E=
  app: frozen-tundra-83422
  on:
    repo: SeanReedy1/node-shopping-list-integration-tests
